targets:
  $default:
    builders:
      ferry_generator|graphql_builder:
        enabled: true
        options:
          schema: personal_finance|lib/schema/schema.graphql
      ferry_generator|serializer_builder:
        enabled: true
        options:
          schema: personal_finance|lib/schema/schema.graphql
